### PR TITLE
Don't use double slash for paths

### PR DESCRIPTION
**Pull request by dereckson**

### CODE REVIEW

**Review by Krinkle — APPROVED** [review]

**Comment by addshore** [comment]
Looks like this one needs a rebase.
The lines touched are now in the "up" script.

**Comment by dereckson** [comment]
Rebased.

**Comment by addshore** [comment]
So, removing the double slashes means the script fails while running on windows.

**Comment by dereckson** [comment]
Abandoned, as the double path is useful on Windows.

**Pull request closed without merging**
