### PR TITLE
T246785 dns in docker network

### PR DESCRIPTION
**Pull request by Silvan-WMDE**
- Add IntelliJ config file to .gitignore
- Open MariaDB port to docker host
- Change internal proxy port and add DNS to docker

### CODE REVIEW

**Comment by addshore** [comment]
Works for me!
I just want to take the mariadb patch out of the chain!

**Comment by addshore** [comment]
Cherry picked onto master:
 https://github.com/addshore/mediawiki-docker-dev/commit/37370e57f7e79af5c8b00c7a3c7e66afe8943778 
https://github.com/addshore/mediawiki-docker-dev/commit/40dc10be5bdd4f716cab5dd8388da78faa29098b

**Comment by Silvan-WMDE** [comment]
This also touches and possibly solves: #12, #47, #70, #92  and #111

**Comment by addshore** [comment]
Interestingly this has broken my debugger connection to host.docker.internal
I will google the problem...

**Pull request closed without merging**
